export const mockData = [
  {
    id: 1,
    jobId: "1000001958",
    name: "John Mwangi",
    source: "EvidCheck",
    date: "23/01/26",
    timestamp: "11:05:42",
    jobTime: "0s",
    product: "CRB Check",
    productSub: "crb_check",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "Clean CRB Credit Listing",
  },
  {
    id: 2,
    jobId: "1000001957",
    name: "Acme Corp Ltd",
    source: "EvidCheck",
    date: "23/01/26",
    timestamp: "09:46:06",
    jobTime: "1s",
    product: "Business Verification",
    productSub: "business_registration",
    idType: "BUSINESS_REGISTRATION",
    country: "KE",
    result: "Approved",
    message: "Business Verified via BRS",
  },
  {
    id: 3,
    jobId: "1000001955",
    name: "Sarah Wanjiku",
    source: "EvidCheck",
    date: "22/01/26",
    timestamp: "20:43:45",
    jobTime: "2s",
    product: "KRA PIN Checker",
    productSub: "kra_pin_check",
    idType: "KRA_PIN",
    country: "KE",
    result: "Approved",
    message: "Tax Obligation Compliant",
  },
  {
    id: 4,
    jobId: "1000001954",
    name: "Peter Ochieng",
    source: "rest_api",
    date: "22/01/26",
    timestamp: "12:57:58",
    jobTime: "1s",
    product: "Individual Document Verification",
    productSub: "national_id",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "National ID Validated via IPRS",
  },
  {
    id: 5,
    jobId: "1000001953",
    name: "Apex Holdings Ltd",
    source: "rest_api",
    date: "22/01/26",
    timestamp: "11:20:10",
    jobTime: "1s",
    product: "Business Verification",
    productSub: "business_registration",
    idType: "BUSINESS_REGISTRATION",
    country: "KE",
    result: "Approved",
    message: "Registration Active & Verified",
  },
  {
    id: 6,
    jobId: "1000001952",
    name: "Brian Odhiambo",
    source: "EvidCheck",
    date: "21/01/26",
    timestamp: "16:45:00",
    jobTime: "1s",
    product: "CRB Check",
    productSub: "crb_check",
    idType: "NATIONAL_ID",
    country: "KE",
    result: "Approved",
    message: "CRB Score 735 - Clean",
  },
];
